module.exports = {
    purge: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
    darkMode: false, // or 'media' or 'class'
    theme: {
        extend: {
            colors: {
                'primary-bg': '#ebecc5',
                'detail-bg': '#e4e3bb',
                'primary-hl': '#68be2f',
                'primary-hl-mo': '#45ad25',
                'primary-bt': '#8a949a',
                'primary-bt-mo': '#7f888f',
                'primary-head': '#173544',
                'primary-head-mo': '#112433',
                'support-err': '#d62828',
                'support-err-mo': '#c71e22',
                'support-alert': '#f77f00',
                'support-alert-mo': '#ef5a00',
                'support-vis-black': '#1a1d1e',
                'support-vis-yellow': '#ffd100',
                'support-vis-blue': '#3fbfdf',
                'white': '#ffffff'
            },
            textColor: {
                'primary-bg': '#ebecc5',
                'detail-bg': '#e4e3bb',
                'primary-hl': '#68be2f',
                'primary-hl-mo': '#45ad25',
                'primary-bt': '#8a949a',
                'primary-bt-mo': '#7f888f',
                'primary-head': '#173544',
                'primary-head-mo': '#112433',
                'support-err': '#d62828',
                'support-err-mo': '#c71e22',
                'support-alert': '#f77f00',
                'support-alert-mo': '#ef5a00',
                'support-vis-black': '#1a1d1e',
                'support-vis-yellow': '#ffd100',
                'support-vis-blue': '#3fbfdf',
                'white': '#ffffff'
            },
            borderColor: theme => ({
                'primary-bg': '#ebecc5',
                'detail-bg': '#e4e3bb',
                'primary-hl': '#68be2f',
                'primary-hl-mo': '#45ad25',
                'primary-bt': '#8a949a',
                'primary-bt-mo': '#7f888f',
                'primary-head': '#173544',
                'primary-head-mo': '#112433',
                'support-err': '#d62828',
                'support-err-mo': '#c71e22',
                'support-alert': '#f77f00',
                'support-alert-mo': '#ef5a00',
                'support-vis-black': '#1a1d1e',
                'support-vis-yellow': '#ffd100',
                'support-vis-blue': '#3fbfdf',
                'white': '#ffffff'
            }),
            width: {
                '1/7': '14.2857142857%',
                '2/7': '28.5714285714%',
                '3/7': '42.8571428571%',
                '4/7': '57.1428571429%',
                '5/7': '71.4285714286%',
                '6/7': '85.7142857143%',
                '1/10': '10%',
                '2/10': '20%',
                '3/10': '30%',
                '4/10': '40%',
                '5/10': '50%',
                '6/10': '60%',
                '7/10': '70%',
                '8/10': '80%',
                '9/10': '90%'
            }
        },
    },
    variants: {
        extend: {},
    },
    plugins: [],
}